"use client";
import {useEffect, useMemo, useState} from "react";
const api=process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
type Event={event_id:string;sequence_no:number;event_type:string;occurred_at:string;payload:Record<string,unknown>};
export default function Home(){
 const [execution,setExecution]=useState(""); const [events,setEvents]=useState<Event[]>([]); const [selected,setSelected]=useState(0); const [state,setState]=useState<any>(); const [error,setError]=useState("");
 const selectedEvent=events[selected];
 async function load(){try {setError(""); const r=await fetch(`${api}/api/v1/executions/${execution}/timeline`); if(!r.ok) throw new Error("Execution not found"); const list=await r.json(); setEvents(list); setSelected(Math.max(0,list.length-1));}catch(e:any){setError(e.message)}}
 useEffect(()=>{if(!selectedEvent)return; fetch(`${api}/api/v1/executions/${execution}/state?event_id=${selectedEvent.event_id}`).then(r=>r.json()).then(x=>setState(x.state));},[selectedEvent,execution]);
 return <main><header><div><small>AGENT TIME MACHINE</small><h1>Temporal debugger for autonomous agents</h1></div><div className="input"><input value={execution} onChange={e=>setExecution(e.target.value)} placeholder="Paste execution UUID"/><button onClick={load}>Inspect</button></div></header>
 {error&&<p className="error">{error}</p>}{events.length>0&&<><section className="timeline"><div className="label">EXECUTION TIMELINE <span>{events.length} immutable events</span></div><input aria-label="Timeline position" type="range" min="0" max={events.length-1} value={selected} onChange={e=>setSelected(Number(e.target.value))}/><div className="ticks">{events.map((e,i)=><button className={i===selected?"active":""} key={e.event_id} onClick={()=>setSelected(i)}>{e.sequence_no}. {e.event_type.replaceAll("_"," ")}</button>)}</div></section>
 <div className="grid"><section><div className="label">HISTORICAL STATE <span>{selectedEvent?.occurred_at}</span></div><State state={state}/></section><section><div className="label">EVENT AT SELECTED POINT</div><pre>{JSON.stringify(selectedEvent,null,2)}</pre><div className="label">EVIDENCE-BACKED INVESTIGATION</div><p>Use the API’s investigation route on a decision to trace decision → belief → evidence. Missing links are reported as insufficient evidence rather than inferred.</p></section></div></>}</main>
}
function State({state}:{state:any}){if(!state)return <p>Reconstructing…</p>; return <div className="state"><Card title="Goal" value={state.goals?.[0]?.statement||"—"}/><Card title="Active Plan" value={state.active_plan?.plan_id||"—"}/><Card title="Beliefs" value={(state.beliefs||[]).map((b:any)=><div key={b.belief_version_id}>{b.status==="active"?"✓":"•"} {b.statement} <b>{Math.round((b.confidence||0)*100)}%</b></div>)}/><Card title="Evidence" value={(state.evidence||[]).map((e:any)=><div key={e.evidence_id}>{e.summary||e.evidence_id}</div>)}/><Card title="Available Tools" value={(state.available_tools||[]).map((t:any)=><div key={t.tool_id}>{t.tool_id} — {t.authorized?"authorized":"not authorized"}</div>)}/><Card title="Actions" value={<>{(state.pending_actions||[]).length} pending · {(state.completed_actions||[]).length} completed</>}/></div>}
function Card({title,value}:{title:string,value:any}){return <article><h3>{title}</h3><div>{value}</div></article>}
