-- PostgreSQL production schema. Events are append-only; application role gets INSERT/SELECT only.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), name text NOT NULL, UNIQUE(organization_id,name));
CREATE TABLE agents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), project_id uuid NOT NULL REFERENCES projects(id), name text NOT NULL);
CREATE TABLE executions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), project_id uuid NOT NULL REFERENCES projects(id), agent_id uuid NOT NULL REFERENCES agents(id), external_key text, status text NOT NULL DEFAULT 'running', started_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, next_sequence_no bigint NOT NULL DEFAULT 1, UNIQUE(agent_id,external_key));
CREATE TABLE events (event_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), project_id uuid NOT NULL REFERENCES projects(id), agent_id uuid NOT NULL REFERENCES agents(id), execution_id uuid NOT NULL REFERENCES executions(id), sequence_no bigint NOT NULL, event_type text NOT NULL, occurred_at timestamptz NOT NULL, ingested_at timestamptz NOT NULL DEFAULT now(), parent_event_id uuid, correlation_id uuid, idempotency_key text, payload jsonb NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', payload_sha256 char(64) NOT NULL, UNIQUE(execution_id,sequence_no), UNIQUE(organization_id,idempotency_key));
CREATE INDEX events_execution_time_idx ON events(execution_id,occurred_at,sequence_no); CREATE INDEX events_agent_time_idx ON events(agent_id,occurred_at DESC); CREATE INDEX events_type_time_idx ON events(event_type,occurred_at DESC);
CREATE TABLE state_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), execution_id uuid NOT NULL REFERENCES executions(id), last_sequence_no bigint NOT NULL, state_schema_version smallint NOT NULL DEFAULT 1, state_document jsonb NOT NULL, state_hash char(64) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(execution_id,last_sequence_no));
CREATE TABLE api_keys (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), project_id uuid REFERENCES projects(id), prefix text NOT NULL, secret_hash text NOT NULL, role text NOT NULL, expires_at timestamptz, revoked_at timestamptz);
CREATE TABLE audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), actor text NOT NULL, action text NOT NULL, resource_type text NOT NULL, resource_id text, correlation_id uuid, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_events ON events USING (organization_id::text = current_setting('app.organization_id', true));
